export const ADD_QUIZ_QUESTIONS = 'ADD_QUIZ_QUESTIONS';
export const ADD_QUIZ_ANSWER = 'ADD_QUIZ_ANSWER';
export const EDIT_QUIZ_ANSWER = 'EDIT_QUIZ_ANSWER';
export const ADD_RESULT_QUESTION = 'ADD_RESULT_QUESTION'; 
export const ADD_USER_RESULT = 'ADD_USER_RESULT';
export const ADD_FINAL_RESULT = 'ADD_FINAL_RESULT'; 

